//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCustomService
    {
        public int CompanyId { get; set; }
        public string Demolition_Services { get; set; }
        public string Disability_Accessibility { get; set; }
        public string Childproofing { get; set; }
        public string Energy_Efficiency_Inspection { get; set; }
        public string Excavation { get; set; }
        public string Biohazard_Cleanup { get; set; }
        public string Mold_Removal { get; set; }
        public string Home_Staging { get; set; }
        public string Inspection_Services { get; set; }
        public string Moving_Services { get; set; }
        public string Restoration { get; set; }
        public string Metal_Restoration { get; set; }
        public string Earthquake_Retrofitting { get; set; }
        public string Epoxy_Flooring_Excavators { get; set; }
        public string Structural_Engineering { get; set; }
        public string Trash_Removal___Hauling { get; set; }
        public string Welding { get; set; }
        public string Mudjacking { get; set; }
        public string Picture_Framing { get; set; }
        public string Woodworking_Services { get; set; }
    
        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
