//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceNewConstruction
    {
        public int CompanyId { get; set; }
        public string Architects { get; set; }
        public string Barns__Gazebos_and_Sheds { get; set; }
        public string Commercial_Construction { get; set; }
        public string Design_Build { get; set; }
        public string Custom_Cabinets___Furniture { get; set; }
        public string Foundation { get; set; }
        public string Garage___Carport_Construction { get; set; }
        public string Home_Additions { get; set; }
        public string Bathtub_Refinishing { get; set; }
        public string Home___Garage_Builders { get; set; }
        public string Land_Clearing___Site_Preparation { get; set; }
        public string New_Home_Construction { get; set; }
        public string Surveyors___Land { get; set; }
    
        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
