//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceExterior
    {
        public int CompanyId { get; set; }
        public string Asphalt_Paving { get; set; }
        public string Awnings { get; set; }
        public string Concrete_Installation___Repair { get; set; }
        public string Decks__Patios___Enclosures { get; set; }
        public string Fence_Install_and_Repair { get; set; }
        public string Gutter_Services { get; set; }
        public string Hurricane_Shutter_Systems { get; set; }
        public string Interlocking___Stonework { get; set; }
        public string Ironwork___Wrought_Iron { get; set; }
        public string Landscaping_Installation { get; set; }
        public string Lawn_Care { get; set; }
        public string Masonry_and_Brick_Work { get; set; }
        public string Power_Washing { get; set; }
        public string Roofing_Services { get; set; }
        public string Siding { get; set; }
        public string Skylights { get; set; }
        public string Sprinkler_Systems_and_Irrigation { get; set; }
        public string Stucco___Plaster { get; set; }
        public string Swimming_Pool_Install { get; set; }
        public string Tree_Service { get; set; }
        public string Waterproofing { get; set; }
        public string Windows___Exterior_Doors { get; set; }
    
        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
