
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentalMobile.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MaintenanceInterior
{

    public int CompanyId { get; set; }

    public bool Basement_Lowering { get; set; }

    public bool Basement_Remodeling { get; set; }

    public bool Bathroom_Remodeling { get; set; }

    public bool Cabinetry_and_Built_ins { get; set; }

    public bool Carpenters { get; set; }

    public bool Carpet_and_Vinyl_Floors { get; set; }

    public bool Ceiling_Install_and_Repair { get; set; }

    public bool Closets_Designing_Organizing { get; set; }

    public bool Counter_Tops { get; set; }

    public bool Remodeling { get; set; }

    public bool Buffing___Polishing { get; set; }

    public bool Drywall { get; set; }

    public bool Carpet_Installation { get; set; }

    public bool Fireplaces___Firewood { get; set; }

    public bool Floor_Heating { get; set; }

    public bool Framing { get; set; }

    public bool Hardwood_and_Laminate_Flooring { get; set; }

    public bool Hardwood_Floor_Refinishing { get; set; }

    public bool Home_Theaters { get; set; }

    public bool Hot_Tubs__Spas___Jacuzzis { get; set; }

    public bool Insulation { get; set; }

    public bool Decorating___Design { get; set; }

    public bool Kitchen_Remodeling { get; set; }

    public bool Non_Slip_Treatments { get; set; }

    public bool Painting_Services { get; set; }

    public bool Solariums_and_Sunrooms { get; set; }

    public bool Tile___Tiling { get; set; }

    public bool Asbestos_Removal { get; set; }

    public bool Wallpaper___Wall_Coverings___Removal { get; set; }



    public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }

}

}
