//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCompanyLookUp
    {
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public int Role { get; set; }
    
        public virtual MaintenanceCompany MaintenanceCompany { get; set; }
        public virtual MaintenanceCompanySpecialization MaintenanceCompanySpecialization { get; set; }
        public virtual MaintenanceCustomService MaintenanceCustomService { get; set; }
        public virtual MaintenanceExterior MaintenanceExterior { get; set; }
        public virtual MaintenanceInterior MaintenanceInterior { get; set; }
        public virtual MaintenanceRepair MaintenanceRepair { get; set; }
        public virtual MaintenanceUtility MaintenanceUtility { get; set; }
        public virtual MaintenanceNewConstruction MaintenanceNewConstruction { get; set; }
    }
}
