//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceInterior
    {
        public int CompanyId { get; set; }
        public string Basement_Lowering { get; set; }
        public string Basement_Remodeling { get; set; }
        public string Bathroom_Remodeling { get; set; }
        public string Cabinetry_and_Built_ins { get; set; }
        public string Carpenters { get; set; }
        public string Carpet_and_Vinyl_Floors { get; set; }
        public string Ceiling_Install_and_Repair { get; set; }
        public string Closets_Designing_Organizing { get; set; }
        public string Counter_Tops { get; set; }
        public string Remodeling { get; set; }
        public string Buffing___Polishing { get; set; }
        public string Drywall { get; set; }
        public string Carpet_Installation { get; set; }
        public string Fireplaces___Firewood { get; set; }
        public string Floor_Heating { get; set; }
        public string Framing { get; set; }
        public string Hardwood_and_Laminate_Flooring { get; set; }
        public string Hardwood_Floor_Refinishing { get; set; }
        public string Home_Theaters { get; set; }
        public string Hot_Tubs__Spas___Jacuzzis { get; set; }
        public string Insulation { get; set; }
        public string Decorating___Design { get; set; }
        public string Kitchen_Remodeling { get; set; }
        public string Non_Slip_Treatments { get; set; }
        public string Painting_Services { get; set; }
        public string Solariums_and_Sunrooms { get; set; }
        public string Tile___Tiling { get; set; }
        public string Asbestos_Removal { get; set; }
        public string Wallpaper___Wall_Coverings___Removal { get; set; }
    
        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
