//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public int ServiceTypeID { get; set; }
        public string Description { get; set; }
        public string PrimaryPhoto { get; set; }
        public string Address { get; set; }
        public string GoogleMap { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> NumberofPhoto { get; set; }
        public Nullable<double> Budget { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public Nullable<int> DaysOnSite { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string PosterRole { get; set; }
        public Nullable<int> PosterID { get; set; }
    }
}
