//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalApplication
    {
        public int ApplicationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string DriverLicense { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string EmailAddress { get; set; }
        public string Income { get; set; }
        public string EmployerPhone { get; set; }
        public string WorkStartDate { get; set; }
        public string WorkEndDate { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerCity { get; set; }
        public string EmployerState { get; set; }
        public string EmployerZipcode { get; set; }
        public string EmployerFax { get; set; }
        public string CoSignerName { get; set; }
        public string CoSignerAddress { get; set; }
        public string CoSignerCity { get; set; }
        public string CoSignerState { get; set; }
        public string CoSignerZipcode { get; set; }
        public string CoSignerPhone { get; set; }
        public string CoSignerRelationShip { get; set; }
        public string OtherOccupant { get; set; }
        public Nullable<bool> Adult { get; set; }
        public string Relationship { get; set; }
    }
}
