//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantSavedSearch
    {
        public int SearchId { get; set; }
        public int TenantId { get; set; }
        public string Search { get; set; }
        public System.DateTime SearchDate { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
