//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitFeature
    {
        public int UnitId { get; set; }
        public bool High_Speed_Internet_Access { get; set; }
        public bool Internet_Included { get; set; }
        public bool Wireless_Internet_Access { get; set; }
        public bool Some_Paid_Utilities { get; set; }
        public bool Covered_Parking { get; set; }
        public bool Pets_allowed { get; set; }
        public bool Cats_Allowed { get; set; }
        public bool Small_Dogs { get; set; }
        public bool Large_Dogs { get; set; }
        public bool Alarm_system { get; set; }
        public bool Near_Transportation { get; set; }
        public bool Short_Term_Lease_Available { get; set; }
        public bool RV_Parking { get; set; }
        public bool Boat_Storage { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
