//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitCommunityAmenity
    {
        public int UnitId { get; set; }
        public Nullable<bool> Neighborhood_Name { get; set; }
        public Nullable<bool> Elementary_School { get; set; }
        public Nullable<bool> High_School { get; set; }
        public Nullable<bool> School_District { get; set; }
        public Nullable<bool> Middle_School { get; set; }
        public Nullable<bool> County_Name { get; set; }
        public Nullable<bool> Assisted_Living_Community { get; set; }
        public Nullable<bool> Over_55_Active_Community { get; set; }
        public Nullable<bool> Disability_Access { get; set; }
        public Nullable<bool> Controlled_Access { get; set; }
        public Nullable<bool> Community_Pool { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
