//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitLuxuryAmenity
    {
        public int UnitId { get; set; }
        public bool Tennis_Court { get; set; }
        public bool Security_System { get; set; }
        public bool Sports_Court { get; set; }
        public bool Basketball_Court { get; set; }
        public bool Fitness_Center { get; set; }
        public bool Barbecue { get; set; }
        public bool Elevator { get; set; }
        public bool Porch { get; set; }
        public bool Sauna { get; set; }
        public bool Skylight { get; set; }
        public bool Intercom { get; set; }
        public bool Waterfront { get; set; }
        public bool Wet_Bar { get; set; }
        public bool Doorman { get; set; }
        public bool Solar_Heat { get; set; }
        public bool Solar_Plumbing { get; set; }
        public bool Solar_Screens { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
