using System;
using System.Collections.Generic;
using RentalMobile.Model.Models;
using RentalMobile.Model.ModelViews;

namespace RentalModel.Repository.Data.Fake
{
    public class FakeAgentRejectedApplication
    { 
       public List<AgentRejectedApplication> MyAgentRejectedApplications;

       public FakeAgentRejectedApplication()
        {
            InitializeAgentRejectedApplicationList();
        }

       public void InitializeAgentRejectedApplicationList()
        {
            MyAgentRejectedApplications = new List<AgentRejectedApplication> {
                FirstAgentRejectedApplication(), 
                SecondAgentRejectedApplication(),
                ThirdAgentRejectedApplication()
            };
        }

       public AgentRejectedApplication FirstAgentRejectedApplication()
        {

            var firstAgentRejectedApplication = new AgentRejectedApplication {

                 ApplicationId = new Int32()
,
                 FirstName = null,
                 LastName = null,
                 MiddleName = null,
                 DateofBirth = new DateTime(),
                 SocialSecurityNumber = null,
                 DriverLicense = null,
                 Phone = null,
                 CellPhone = null,
                 EmailAddress = null,
                 CoSignerName = null,
                 CoSignerAddress = null,
                 CoSignerCity = null,
                 CoSignerState = null,
                 CoSignerZipcode = null,
                 CoSignerPhone = null,
                 CoSignerRelationShip = null,
                 CoSignerEmailAddress = null,
                 OtherOccupant1Name = null,
                 IsOccupant1Adult = new Boolean(),
                 RelationshipOccupant1ToApplicant = null,
                 OtherOccupant2Name = null,
                 IsOccupant2Adult = new Boolean(),
                 RelationshipOccupant2ToApplicant = null,
                 OtherOccupant3Name = null,
                 IsOccupant3Adult = new Boolean(),
                 RelationshipOccupant3ToApplicant = null,
                 OtherOccupant4Name = null,
                 IsOccupant4Adult = new Boolean(),
                 RelationshipOccupant4ToApplicant = null,
                 EmployerName = null,
                 Income = null,
                 WorkStartDate = new DateTime(),
                 WorkEndDate = new DateTime(),
                 EmployerAddress = null,
                 EmployerCity = null,
                 EmployerState = null,
                 EmployerZipcode = null,
                 EmployerPhone = null,
                 EmployerFax = null,
                 CurrentLandloard = null,
                 CurrentLandLoardPhone = null,
                 CurrentLandLoardFax = null,
                 CurrentAddress = null,
                 CurrentAddressCity = null,
                 CurrentAddressState = null,
                 CurrentAddressZip = null,
                 Rent = null,
                 CurrentRentStartDate = new DateTime(),
                 CurrentRentEndDate = new DateTime(),
                 PreviousLandloard = null,
                 PreviousLandLoardPhone = null,
                 PreviousLandLoardFax = null,
                 PreviousAddress = null,
                 PreviousAddressCity = null,
                 PreviousAddressState = null,
                 PreviousAddressZip = null,
                 PreviousRent = null,
                 PreviousRentStartDate = new DateTime(),
                 PreviousRentEndDate = new DateTime(),
                 EmergencyContactName = null,
                 EmergencyContactRelationShip = null,
                 EmergencyContactPhone = null,
                 EmergencyContactAddress = null,
                 EmergencyContactCity = null,
                 EmergencyContactState = null,
                 EmergencyContactZipCode = null,
                 Pets = new Boolean(),
                 PetsNumber = new Int32(),
                 Pet1Brand = null,
                 Pet1Age = new Int32(),
                 Pet1Weight = null,
                 Pet2Brand = null,
                 Pet2Age = new Int32(),
                 Pet2Weight = null,
                 Vehicle1Make = null,
                 Vehicle1Model = null,
                 Vehicle1Year = new Int32(),
                 Vehicle1Color = null,
                 Vehicle1LicensePlate = null,
                 Vehicle2Make = null,
                 Vehicle2Model = null,
                 Vehicle2Year = new Int32(),
                 Vehicle2Color = null,
                 Vehicle2LicensePlate = null,
                 Vehicle3Make = null,
                 Vehicle3Model = null,
                 Vehicle3Year = new Int32(),
                 Vehicle3Color = null,
                 Vehicle3LicensePlate = null,
                 Vehicle4Make = null,
                 Vehicle4Model = null,
                 Vehicle4Year = new Int32(),
                 Vehicle4Color = null,
                 Vehicle4LicensePlate = null,
                 Bankruptcy = new Boolean(),
                 LeaseDefaulted = new Boolean(),
                 RefusedtoPayRent = new Boolean(),
                 EvictedFromRental = new Boolean(),
                 ConvictedofFelony = new Boolean(),
                 TenantId = new Int32(),
                 AgentId = new Int32()

    
 };

            return firstAgentRejectedApplication;
        }

       public AgentRejectedApplication SecondAgentRejectedApplication()
        {

            var secondAgentRejectedApplication = new AgentRejectedApplication {

                 ApplicationId = new Int32()
,
                 FirstName = null,
                 LastName = null,
                 MiddleName = null,
                 DateofBirth = new DateTime(),
                 SocialSecurityNumber = null,
                 DriverLicense = null,
                 Phone = null,
                 CellPhone = null,
                 EmailAddress = null,
                 CoSignerName = null,
                 CoSignerAddress = null,
                 CoSignerCity = null,
                 CoSignerState = null,
                 CoSignerZipcode = null,
                 CoSignerPhone = null,
                 CoSignerRelationShip = null,
                 CoSignerEmailAddress = null,
                 OtherOccupant1Name = null,
                 IsOccupant1Adult = new Boolean(),
                 RelationshipOccupant1ToApplicant = null,
                 OtherOccupant2Name = null,
                 IsOccupant2Adult = new Boolean(),
                 RelationshipOccupant2ToApplicant = null,
                 OtherOccupant3Name = null,
                 IsOccupant3Adult = new Boolean(),
                 RelationshipOccupant3ToApplicant = null,
                 OtherOccupant4Name = null,
                 IsOccupant4Adult = new Boolean(),
                 RelationshipOccupant4ToApplicant = null,
                 EmployerName = null,
                 Income = null,
                 WorkStartDate = new DateTime(),
                 WorkEndDate = new DateTime(),
                 EmployerAddress = null,
                 EmployerCity = null,
                 EmployerState = null,
                 EmployerZipcode = null,
                 EmployerPhone = null,
                 EmployerFax = null,
                 CurrentLandloard = null,
                 CurrentLandLoardPhone = null,
                 CurrentLandLoardFax = null,
                 CurrentAddress = null,
                 CurrentAddressCity = null,
                 CurrentAddressState = null,
                 CurrentAddressZip = null,
                 Rent = null,
                 CurrentRentStartDate = new DateTime(),
                 CurrentRentEndDate = new DateTime(),
                 PreviousLandloard = null,
                 PreviousLandLoardPhone = null,
                 PreviousLandLoardFax = null,
                 PreviousAddress = null,
                 PreviousAddressCity = null,
                 PreviousAddressState = null,
                 PreviousAddressZip = null,
                 PreviousRent = null,
                 PreviousRentStartDate = new DateTime(),
                 PreviousRentEndDate = new DateTime(),
                 EmergencyContactName = null,
                 EmergencyContactRelationShip = null,
                 EmergencyContactPhone = null,
                 EmergencyContactAddress = null,
                 EmergencyContactCity = null,
                 EmergencyContactState = null,
                 EmergencyContactZipCode = null,
                 Pets = new Boolean(),
                 PetsNumber = new Int32(),
                 Pet1Brand = null,
                 Pet1Age = new Int32(),
                 Pet1Weight = null,
                 Pet2Brand = null,
                 Pet2Age = new Int32(),
                 Pet2Weight = null,
                 Vehicle1Make = null,
                 Vehicle1Model = null,
                 Vehicle1Year = new Int32(),
                 Vehicle1Color = null,
                 Vehicle1LicensePlate = null,
                 Vehicle2Make = null,
                 Vehicle2Model = null,
                 Vehicle2Year = new Int32(),
                 Vehicle2Color = null,
                 Vehicle2LicensePlate = null,
                 Vehicle3Make = null,
                 Vehicle3Model = null,
                 Vehicle3Year = new Int32(),
                 Vehicle3Color = null,
                 Vehicle3LicensePlate = null,
                 Vehicle4Make = null,
                 Vehicle4Model = null,
                 Vehicle4Year = new Int32(),
                 Vehicle4Color = null,
                 Vehicle4LicensePlate = null,
                 Bankruptcy = new Boolean(),
                 LeaseDefaulted = new Boolean(),
                 RefusedtoPayRent = new Boolean(),
                 EvictedFromRental = new Boolean(),
                 ConvictedofFelony = new Boolean(),
                 TenantId = new Int32(),
                 AgentId = new Int32()

        
 };

            return secondAgentRejectedApplication;
        }

       public AgentRejectedApplication ThirdAgentRejectedApplication()
        {

            var thirdAgentRejectedApplication = new AgentRejectedApplication {

                 ApplicationId = new Int32()
,
                 FirstName = null,
                 LastName = null,
                 MiddleName = null,
                 DateofBirth = new DateTime(),
                 SocialSecurityNumber = null,
                 DriverLicense = null,
                 Phone = null,
                 CellPhone = null,
                 EmailAddress = null,
                 CoSignerName = null,
                 CoSignerAddress = null,
                 CoSignerCity = null,
                 CoSignerState = null,
                 CoSignerZipcode = null,
                 CoSignerPhone = null,
                 CoSignerRelationShip = null,
                 CoSignerEmailAddress = null,
                 OtherOccupant1Name = null,
                 IsOccupant1Adult = new Boolean(),
                 RelationshipOccupant1ToApplicant = null,
                 OtherOccupant2Name = null,
                 IsOccupant2Adult = new Boolean(),
                 RelationshipOccupant2ToApplicant = null,
                 OtherOccupant3Name = null,
                 IsOccupant3Adult = new Boolean(),
                 RelationshipOccupant3ToApplicant = null,
                 OtherOccupant4Name = null,
                 IsOccupant4Adult = new Boolean(),
                 RelationshipOccupant4ToApplicant = null,
                 EmployerName = null,
                 Income = null,
                 WorkStartDate = new DateTime(),
                 WorkEndDate = new DateTime(),
                 EmployerAddress = null,
                 EmployerCity = null,
                 EmployerState = null,
                 EmployerZipcode = null,
                 EmployerPhone = null,
                 EmployerFax = null,
                 CurrentLandloard = null,
                 CurrentLandLoardPhone = null,
                 CurrentLandLoardFax = null,
                 CurrentAddress = null,
                 CurrentAddressCity = null,
                 CurrentAddressState = null,
                 CurrentAddressZip = null,
                 Rent = null,
                 CurrentRentStartDate = new DateTime(),
                 CurrentRentEndDate = new DateTime(),
                 PreviousLandloard = null,
                 PreviousLandLoardPhone = null,
                 PreviousLandLoardFax = null,
                 PreviousAddress = null,
                 PreviousAddressCity = null,
                 PreviousAddressState = null,
                 PreviousAddressZip = null,
                 PreviousRent = null,
                 PreviousRentStartDate = new DateTime(),
                 PreviousRentEndDate = new DateTime(),
                 EmergencyContactName = null,
                 EmergencyContactRelationShip = null,
                 EmergencyContactPhone = null,
                 EmergencyContactAddress = null,
                 EmergencyContactCity = null,
                 EmergencyContactState = null,
                 EmergencyContactZipCode = null,
                 Pets = new Boolean(),
                 PetsNumber = new Int32(),
                 Pet1Brand = null,
                 Pet1Age = new Int32(),
                 Pet1Weight = null,
                 Pet2Brand = null,
                 Pet2Age = new Int32(),
                 Pet2Weight = null,
                 Vehicle1Make = null,
                 Vehicle1Model = null,
                 Vehicle1Year = new Int32(),
                 Vehicle1Color = null,
                 Vehicle1LicensePlate = null,
                 Vehicle2Make = null,
                 Vehicle2Model = null,
                 Vehicle2Year = new Int32(),
                 Vehicle2Color = null,
                 Vehicle2LicensePlate = null,
                 Vehicle3Make = null,
                 Vehicle3Model = null,
                 Vehicle3Year = new Int32(),
                 Vehicle3Color = null,
                 Vehicle3LicensePlate = null,
                 Vehicle4Make = null,
                 Vehicle4Model = null,
                 Vehicle4Year = new Int32(),
                 Vehicle4Color = null,
                 Vehicle4LicensePlate = null,
                 Bankruptcy = new Boolean(),
                 LeaseDefaulted = new Boolean(),
                 RefusedtoPayRent = new Boolean(),
                 EvictedFromRental = new Boolean(),
                 ConvictedofFelony = new Boolean(),
                 TenantId = new Int32(),
                 AgentId = new Int32()

 
 };

            return thirdAgentRejectedApplication;
        }

        ~FakeAgentRejectedApplication()
        {
            MyAgentRejectedApplications = null;
        }
    }
}


    