using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RentalMobile.Helpers.Base;
using RentalMobile.Helpers.Core;
using RentalMobile.Helpers.Membership;
using RentalMobile.Model.Models;
using RentalModel.Repository.Generic.UnitofWork;

namespace RentalMobile.Helpers.Process.Application
{
    public class TenantRentalApplicationHelper : BaseController, ITenantRentalApplication
    {
        public TenantRentalApplicationHelper(IGenericUnitofWork uow, IMembershipService membershipService)
        {
            MembershipService = membershipService;
            UnitofWork = uow;
        }

        public void InsertOwnerPendingApplication(RentalApplication r, int ownerId)
        {

            var opa = new OwnerPendingApplication
            {
                FirstName = r.FirstName,
                LastName = r.LastName,
                MiddleName = r.MiddleName,
                SocialSecurityNumber = r.SocialSecurityNumber,
                DriverLicense = r.DriverLicense,
                Phone = r.Phone,
                CellPhone = r.CellPhone,
                EmailAddress = r.EmailAddress,
                CoSignerName = r.CoSignerName,
                CoSignerAddress = r.CoSignerAddress,
                CoSignerCity = r.CoSignerCity,
                CoSignerState = r.CoSignerState,
                CoSignerZipcode = r.CoSignerZipcode,
                CoSignerPhone = r.CoSignerPhone,
                CoSignerRelationShip = r.CoSignerRelationShip,
                CoSignerEmailAddress = r.CoSignerEmailAddress,
                OtherOccupant1Name = r.OtherOccupant1Name,
                IsOccupant1Adult = r.IsOccupant1Adult,
                RelationshipOccupant1ToApplicant = r.RelationshipOccupant1ToApplicant,
                OtherOccupant2Name = r.OtherOccupant2Name,
                IsOccupant2Adult = r.IsOccupant2Adult,
                RelationshipOccupant2ToApplicant = r.RelationshipOccupant2ToApplicant,
                OtherOccupant3Name = r.OtherOccupant3Name,
                IsOccupant3Adult = r.IsOccupant3Adult,
                RelationshipOccupant3ToApplicant = r.RelationshipOccupant3ToApplicant,
                OtherOccupant4Name = r.OtherOccupant4Name,
                IsOccupant4Adult = r.IsOccupant4Adult,
                RelationshipOccupant4ToApplicant = r.RelationshipOccupant4ToApplicant,
                EmployerName = r.EmployerName,
                Income = r.Income,
                WorkStartDate = r.WorkStartDate,
                WorkEndDate = r.WorkEndDate,
                EmployerAddress = r.EmployerAddress,
                EmployerCity = r.EmployerCity,
                EmployerState = r.EmployerState,
                EmployerZipcode = r.EmployerZipcode,
                EmployerPhone = r.EmployerPhone,
                EmployerFax = r.EmployerFax,
                CurrentLandloard = r.CurrentLandloard,
                CurrentLandLoardPhone = r.CurrentLandLoardPhone,
                CurrentLandLoardFax = r.CurrentLandLoardFax,
                CurrentAddress = r.CurrentAddress,
                CurrentAddressCity = r.CurrentAddressCity,
                CurrentAddressState = r.CurrentAddressState,
                CurrentAddressZip = r.CurrentAddressZip,
                Rent = r.Rent,
                CurrentRentStartDate = r.CurrentRentStartDate,
                CurrentRentEndDate = r.CurrentRentEndDate,
                PreviousLandloard = r.PreviousLandloard,
                PreviousLandLoardPhone = r.PreviousLandLoardPhone,
                PreviousLandLoardFax = r.PreviousLandLoardFax,
                PreviousAddress = r.PreviousAddress,
                PreviousAddressCity = r.PreviousAddressCity,
                PreviousAddressState = r.PreviousAddressState,
                PreviousAddressZip = r.PreviousAddressZip,
                PreviousRent = r.PreviousRent,
                PreviousRentStartDate = r.PreviousRentStartDate,
                PreviousRentEndDate = r.PreviousRentEndDate,
                EmergencyContactName = r.EmergencyContactName,
                EmergencyContactRelationShip = r.EmergencyContactRelationShip,
                EmergencyContactPhone = r.EmergencyContactPhone,
                EmergencyContactAddress = r.EmergencyContactAddress,
                EmergencyContactCity = r.EmergencyContactCity,
                EmergencyContactState = r.EmergencyContactState,
                EmergencyContactZipCode = r.EmergencyContactZipCode,
                Pets = r.Pets,
                PetsNumber = r.PetsNumber,
                Pet1Brand = r.Pet1Brand,
                Pet1Age = r.Pet1Age,
                Pet1Weight = r.Pet1Weight,
                Pet2Brand = r.Pet2Brand,
                Pet2Age = r.Pet2Age,
                Pet2Weight = r.Pet2Weight,
                Vehicle1Make = r.Vehicle1Make,
                Vehicle1Model = r.Vehicle1Model,
                Vehicle1Year = r.Vehicle1Year,
                Vehicle1Color = r.Vehicle1Color,
                Vehicle1LicensePlate = r.Vehicle1LicensePlate,
                Vehicle2Make = r.Vehicle2Make,
                Vehicle2Model = r.Vehicle2Model,
                Vehicle2Year = r.Vehicle2Year,
                Vehicle2Color = r.Vehicle2Color,
                Vehicle2LicensePlate = r.Vehicle2LicensePlate,
                Vehicle3Make = r.Vehicle3Make,
                Vehicle3Model = r.Vehicle3Model,
                Vehicle3Year = r.Vehicle3Year,
                Vehicle3Color = r.Vehicle3Color,
                Vehicle3LicensePlate = r.Vehicle3LicensePlate,
                Vehicle4Make = r.Vehicle4Make,
                Vehicle4Model = r.Vehicle4Model,
                Vehicle4Year = r.Vehicle4Year,
                Vehicle4Color = r.Vehicle4Color,
                Vehicle4LicensePlate = r.Vehicle4LicensePlate,
                Bankruptcy = r.Bankruptcy,
                LeaseDefaulted = r.LeaseDefaulted,
                RefusedtoPayRent = r.RefusedtoPayRent,
                EvictedFromRental = r.EvictedFromRental,
                ConvictedofFelony = r.ConvictedofFelony,
                TenantId = r.TenantId,
                OwnerId = ownerId
            };

            UnitofWork.OwnerPendingApplicationRepository.Add(opa);
            UnitofWork.Save();
        }

        public void InsertAgentPendingApplication(RentalApplication r, int agentId)
        {
            var apa = new AgentPendingApplication
            {
                FirstName = r.FirstName,
                LastName = r.LastName,
                MiddleName = r.MiddleName,
                SocialSecurityNumber = r.SocialSecurityNumber,
                DriverLicense = r.DriverLicense,
                Phone = r.Phone,
                CellPhone = r.CellPhone,
                EmailAddress = r.EmailAddress,
                CoSignerName = r.CoSignerName,
                CoSignerAddress = r.CoSignerAddress,
                CoSignerCity = r.CoSignerCity,
                CoSignerState = r.CoSignerState,
                CoSignerZipcode = r.CoSignerZipcode,
                CoSignerPhone = r.CoSignerPhone,
                CoSignerRelationShip = r.CoSignerRelationShip,
                CoSignerEmailAddress = r.CoSignerEmailAddress,
                OtherOccupant1Name = r.OtherOccupant1Name,
                IsOccupant1Adult = r.IsOccupant1Adult,
                RelationshipOccupant1ToApplicant = r.RelationshipOccupant1ToApplicant,
                OtherOccupant2Name = r.OtherOccupant2Name,
                IsOccupant2Adult = r.IsOccupant2Adult,
                RelationshipOccupant2ToApplicant = r.RelationshipOccupant2ToApplicant,
                OtherOccupant3Name = r.OtherOccupant3Name,
                IsOccupant3Adult = r.IsOccupant3Adult,
                RelationshipOccupant3ToApplicant = r.RelationshipOccupant3ToApplicant,
                OtherOccupant4Name = r.OtherOccupant4Name,
                IsOccupant4Adult = r.IsOccupant4Adult,
                RelationshipOccupant4ToApplicant = r.RelationshipOccupant4ToApplicant,
                EmployerName = r.EmployerName,
                Income = r.Income,
                WorkStartDate = r.WorkStartDate,
                WorkEndDate = r.WorkEndDate,
                EmployerAddress = r.EmployerAddress,
                EmployerCity = r.EmployerCity,
                EmployerState = r.EmployerState,
                EmployerZipcode = r.EmployerZipcode,
                EmployerPhone = r.EmployerPhone,
                EmployerFax = r.EmployerFax,
                CurrentLandloard = r.CurrentLandloard,
                CurrentLandLoardPhone = r.CurrentLandLoardPhone,
                CurrentLandLoardFax = r.CurrentLandLoardFax,
                CurrentAddress = r.CurrentAddress,
                CurrentAddressCity = r.CurrentAddressCity,
                CurrentAddressState = r.CurrentAddressState,
                CurrentAddressZip = r.CurrentAddressZip,
                Rent = r.Rent,
                CurrentRentStartDate = r.CurrentRentStartDate,
                CurrentRentEndDate = r.CurrentRentEndDate,
                PreviousLandloard = r.PreviousLandloard,
                PreviousLandLoardPhone = r.PreviousLandLoardPhone,
                PreviousLandLoardFax = r.PreviousLandLoardFax,
                PreviousAddress = r.PreviousAddress,
                PreviousAddressCity = r.PreviousAddressCity,
                PreviousAddressState = r.PreviousAddressState,
                PreviousAddressZip = r.PreviousAddressZip,
                PreviousRent = r.PreviousRent,
                PreviousRentStartDate = r.PreviousRentStartDate,
                PreviousRentEndDate = r.PreviousRentEndDate,
                EmergencyContactName = r.EmergencyContactName,
                EmergencyContactRelationShip = r.EmergencyContactRelationShip,
                EmergencyContactPhone = r.EmergencyContactPhone,
                EmergencyContactAddress = r.EmergencyContactAddress,
                EmergencyContactCity = r.EmergencyContactCity,
                EmergencyContactState = r.EmergencyContactState,
                EmergencyContactZipCode = r.EmergencyContactZipCode,
                Pets = r.Pets,
                PetsNumber = r.PetsNumber,
                Pet1Brand = r.Pet1Brand,
                Pet1Age = r.Pet1Age,
                Pet1Weight = r.Pet1Weight,
                Pet2Brand = r.Pet2Brand,
                Pet2Age = r.Pet2Age,
                Pet2Weight = r.Pet2Weight,
                Vehicle1Make = r.Vehicle1Make,
                Vehicle1Model = r.Vehicle1Model,
                Vehicle1Year = r.Vehicle1Year,
                Vehicle1Color = r.Vehicle1Color,
                Vehicle1LicensePlate = r.Vehicle1LicensePlate,
                Vehicle2Make = r.Vehicle2Make,
                Vehicle2Model = r.Vehicle2Model,
                Vehicle2Year = r.Vehicle2Year,
                Vehicle2Color = r.Vehicle2Color,
                Vehicle2LicensePlate = r.Vehicle2LicensePlate,
                Vehicle3Make = r.Vehicle3Make,
                Vehicle3Model = r.Vehicle3Model,
                Vehicle3Year = r.Vehicle3Year,
                Vehicle3Color = r.Vehicle3Color,
                Vehicle3LicensePlate = r.Vehicle3LicensePlate,
                Vehicle4Make = r.Vehicle4Make,
                Vehicle4Model = r.Vehicle4Model,
                Vehicle4Year = r.Vehicle4Year,
                Vehicle4Color = r.Vehicle4Color,
                Vehicle4LicensePlate = r.Vehicle4LicensePlate,
                Bankruptcy = r.Bankruptcy,
                LeaseDefaulted = r.LeaseDefaulted,
                RefusedtoPayRent = r.RefusedtoPayRent,
                EvictedFromRental = r.EvictedFromRental,
                ConvictedofFelony = r.ConvictedofFelony,
                TenantId = r.TenantId,
                AgentId = agentId
            };
            UnitofWork.AgentPendingApplicationRepository.Add(apa);
            UnitofWork.Save();
        }

    }
}