
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace RentalMobile.Model.Models
{
    public partial class MaintenanceProviderAcceptedJob
{

    public int MaintenanceProviderId { get; set; }

    public Nullable<int> TenantId { get; set; }

    public string TenantName { get; set; }

    public string TenantEmailAddress { get; set; }

    public Nullable<int> PropertyId { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

}

}
