
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentalMobile.Model.Models
{
    public partial class MaintenanceNewConstruction
{

    public int CompanyId { get; set; }

    public bool Architects { get; set; }

    public bool Barns__Gazebos_and_Sheds { get; set; }

    public bool Commercial_Construction { get; set; }

    public bool Design_Build { get; set; }

    public bool Custom_Cabinets___Furniture { get; set; }

    public bool Foundation { get; set; }

    public bool Garage___Carport_Construction { get; set; }

    public bool Home_Additions { get; set; }

    public bool Bathtub_Refinishing { get; set; }

    public bool Home___Garage_Builders { get; set; }

    public bool Land_Clearing___Site_Preparation { get; set; }

    public bool New_Home_Construction { get; set; }

    public bool Surveyors___Land { get; set; }



    public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }

}

}
