
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentalMobile.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MaintenanceCustomService
{

    public int CompanyId { get; set; }

    public bool Demolition_Services { get; set; }

    public bool Disability_Accessibility { get; set; }

    public bool Childproofing { get; set; }

    public bool Energy_Efficiency_Inspection { get; set; }

    public bool Excavation { get; set; }

    public bool Biohazard_Cleanup { get; set; }

    public bool Mold_Removal { get; set; }

    public bool Home_Staging { get; set; }

    public bool Inspection_Services { get; set; }

    public bool Moving_Services { get; set; }

    public bool Restoration { get; set; }

    public bool Metal_Restoration { get; set; }

    public bool Earthquake_Retrofitting { get; set; }

    public bool Epoxy_Flooring_Excavators { get; set; }

    public bool Structural_Engineering { get; set; }

    public bool Trash_Removal___Hauling { get; set; }

    public bool Welding { get; set; }

    public bool Mudjacking { get; set; }

    public bool Picture_Framing { get; set; }

    public bool Woodworking_Services { get; set; }



    public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }

}

}
