//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCompanySpecialization
    {
        public int CompanyId { get; set; }
        public int Years_Experience { get; set; }
        public int NumberofEmployee { get; set; }
        public int NumberofCertifitedEmplyee { get; set; }
        public bool Air_Conditioning { get; set; }
        public bool Electrical { get; set; }
        public bool Kitchen_Remodeling { get; set; }
        public bool Architects { get; set; }
        public bool Flooring { get; set; }
        public bool Landscaping { get; set; }
        public bool Asphalt_Paving { get; set; }
        public bool General_Contracting { get; set; }
        public bool Painting { get; set; }
        public bool Basement_Finishing { get; set; }
        public bool Handyman_Services { get; set; }
        public bool Plumbing { get; set; }
        public bool Bathroom_Remodeling { get; set; }
        public bool Heating { get; set; }
        public bool Roofing { get; set; }
        public bool Concrete { get; set; }
        public bool Home_Addition_Construction { get; set; }
        public bool Siding { get; set; }
        public bool Deck_Construction { get; set; }
        public bool Home_Construction { get; set; }
        public bool Tiling { get; set; }
        public bool IsInsured { get; set; }
        public double Rate { get; set; }
        public string Currency { get; set; }
        public int CurrencyID { get; set; }


        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
