//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceUtility
    {
        public int CompanyId { get; set; }
        public bool Security_Systems___Automation { get; set; }
        public bool Central_Vacuum { get; set; }
        public bool Electrical { get; set; }
        public bool Energy_Audit { get; set; }
        public bool Gas___Propane_Services { get; set; }
        public bool Heating___Air_Conditioning { get; set; }
        public bool Lighting_Services { get; set; }
        public bool Plumbing { get; set; }
        public bool Satellite_Dish_Systems { get; set; }
        public bool Sewer___Septic_Services { get; set; }
        public bool Solar_Panels___Energy { get; set; }
        public bool Voice___Data_Wiring_Install___Repair { get; set; }
        public bool Radon_Testing { get; set; }
        public bool Water_Heaters___Pumps { get; set; }
        public bool Water_Purification___Softening { get; set; }
    
        public virtual MaintenanceCompanyLookUp MaintenanceCompanyLookUp { get; set; }
    }
}
