//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RentalMobile.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceCompanyLookUp
    {
        [Key]
        public int CompanyId { get; set; }

        public int UserId { get; set; }
        public int Role { get; set; }
    
        public virtual MaintenanceCompany MaintenanceCompany { get; set; }
        public virtual MaintenanceExterior MaintenanceExterior { get; set; }
        public virtual MaintenanceInterior MaintenanceInterior { get; set; }
        public virtual MaintenanceNewConstruction MaintenanceNewConstruction { get; set; }
        public virtual MaintenanceRepair MaintenanceRepair { get; set; }
        public virtual MaintenanceUtility MaintenanceUtility { get; set; }
    }
}
