//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalContext : DbContext
    {
        public RentalContext()
            : base("name=RentalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentAcceptedApplication> AgentAcceptedApplications { get; set; }
        public virtual DbSet<AgentAcceptedPostedProject> AgentAcceptedPostedProjects { get; set; }
        public virtual DbSet<AgentPendingApplication> AgentPendingApplications { get; set; }
        public virtual DbSet<AgentPendingPostedProject> AgentPendingPostedProjects { get; set; }
        public virtual DbSet<AgentProject> AgentProjects { get; set; }
        public virtual DbSet<AgentRejectedApplication> AgentRejectedApplications { get; set; }
        public virtual DbSet<AgentRejectedPostedProject> AgentRejectedPostedProjects { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<Basement> Basements { get; set; }
        public virtual DbSet<Bathroom> Bathrooms { get; set; }
        public virtual DbSet<Bed> Beds { get; set; }
        public virtual DbSet<Cooling> Coolings { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Floor> Floors { get; set; }
        public virtual DbSet<FloorCovering> FloorCoverings { get; set; }
        public virtual DbSet<Foundation> Foundations { get; set; }
        public virtual DbSet<Garage> Garages { get; set; }
        public virtual DbSet<GeneratedRentalContract> GeneratedRentalContracts { get; set; }
        public virtual DbSet<Heating> Heatings { get; set; }
        public virtual DbSet<MaintenanceCompany> MaintenanceCompanies { get; set; }
        public virtual DbSet<MaintenanceCompanyLookUp> MaintenanceCompanyLookUps { get; set; }
        public virtual DbSet<MaintenanceCompanySpecialization> MaintenanceCompanySpecializations { get; set; }
        public virtual DbSet<MaintenanceCrew> MaintenanceCrews { get; set; }
        public virtual DbSet<MaintenanceCustomService> MaintenanceCustomServices { get; set; }
        public virtual DbSet<MaintenanceExterior> MaintenanceExteriors { get; set; }
        public virtual DbSet<MaintenanceInterior> MaintenanceInteriors { get; set; }
        public virtual DbSet<MaintenanceNewConstruction> MaintenanceNewConstructions { get; set; }
        public virtual DbSet<MaintenanceOrder> MaintenanceOrders { get; set; }
        public virtual DbSet<MaintenancePhoto> MaintenancePhotoes { get; set; }
        public virtual DbSet<MaintenanceProvider> MaintenanceProviders { get; set; }
        public virtual DbSet<MaintenanceProviderAcceptedJob> MaintenanceProviderAcceptedJobs { get; set; }
        public virtual DbSet<MaintenanceProviderNewJobOffer> MaintenanceProviderNewJobOffers { get; set; }
        public virtual DbSet<MaintenanceProviderRejectedJob> MaintenanceProviderRejectedJobs { get; set; }
        public virtual DbSet<MaintenanceProviderZone> MaintenanceProviderZones { get; set; }
        public virtual DbSet<MaintenanceRepair> MaintenanceRepairs { get; set; }
        public virtual DbSet<MaintenanceTeam> MaintenanceTeams { get; set; }
        public virtual DbSet<MaintenanceTeamAssociation> MaintenanceTeamAssociations { get; set; }
        public virtual DbSet<MaintenanceUtility> MaintenanceUtilities { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<OwnerAcceptedApplication> OwnerAcceptedApplications { get; set; }
        public virtual DbSet<OwnerAcceptedPostedProject> OwnerAcceptedPostedProjects { get; set; }
        public virtual DbSet<OwnerMaintenance> OwnerMaintenances { get; set; }
        public virtual DbSet<OwnerPendingApplication> OwnerPendingApplications { get; set; }
        public virtual DbSet<OwnerPendingPostedProject> OwnerPendingPostedProjects { get; set; }
        public virtual DbSet<OwnerPendingShowingCalendar> OwnerPendingShowingCalendars { get; set; }
        public virtual DbSet<OwnerProject> OwnerProjects { get; set; }
        public virtual DbSet<OwnerRejectedApplication> OwnerRejectedApplications { get; set; }
        public virtual DbSet<OwnerRejectedPostedProject> OwnerRejectedPostedProjects { get; set; }
        public virtual DbSet<OwnerShowingCalendar> OwnerShowingCalendars { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectPhoto> ProjectPhotoes { get; set; }
        public virtual DbSet<ProviderProfileComment> ProviderProfileComments { get; set; }
        public virtual DbSet<ProviderWork> ProviderWorks { get; set; }
        public virtual DbSet<RentalApplication> RentalApplications { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<Specialist> Specialists { get; set; }
        public virtual DbSet<SpecialistPendingTeamInvitation> SpecialistPendingTeamInvitations { get; set; }
        public virtual DbSet<SpecialistProfileComment> SpecialistProfileComments { get; set; }
        public virtual DbSet<SpecialistWork> SpecialistWorks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<TenantFavorite> TenantFavorites { get; set; }
        public virtual DbSet<TenantMaintenance> TenantMaintenances { get; set; }
        public virtual DbSet<TenantSavedSearch> TenantSavedSearches { get; set; }
        public virtual DbSet<TenantShowing> TenantShowings { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitAppliance> UnitAppliances { get; set; }
        public virtual DbSet<UnitCommunityAmenity> UnitCommunityAmenities { get; set; }
        public virtual DbSet<UnitExteriorAmenity> UnitExteriorAmenities { get; set; }
        public virtual DbSet<UnitFeature> UnitFeatures { get; set; }
        public virtual DbSet<UnitGallery> UnitGalleries { get; set; }
        public virtual DbSet<UnitInteriorAmenity> UnitInteriorAmenities { get; set; }
        public virtual DbSet<UnitLuxuryAmenity> UnitLuxuryAmenities { get; set; }
        public virtual DbSet<UnitPricing> UnitPricings { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<UploadedContract> UploadedContracts { get; set; }
        public virtual DbSet<UrgencyType> UrgencyTypes { get; set; }
        public virtual DbSet<ParkingSpace> ParkingSpaces { get; set; }
    }
}
