
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RentalMobile.Model.Models
{
    public partial class UploadedContract
{

    public int UploadedImageId { get; set; }

    public string UploadedImagePath { get; set; }

    public int UploaderId { get; set; }

    public string UploaderRole { get; set; }

}

}
