ALTER TABLE [dbo].[MaintenanceExteriors]
    ADD CONSTRAINT [PK_[MaintenanceExteriorHome ImprovementsandRepairs] PRIMARY KEY CLUSTERED ([CompanyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

