ALTER TABLE [dbo].[Agent]
    ADD CONSTRAINT [PK_Agent] PRIMARY KEY CLUSTERED ([AgentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

