ALTER TABLE [dbo].[Basement]
    ADD CONSTRAINT [PK_Basement] PRIMARY KEY CLUSTERED ([BasementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

