ALTER TABLE [dbo].[Beds]
    ADD CONSTRAINT [PK_Beds] PRIMARY KEY CLUSTERED ([BedID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

