ALTER TABLE [dbo].[Cooling]
    ADD CONSTRAINT [PK_Cooling] PRIMARY KEY CLUSTERED ([CoolingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

