ALTER TABLE [dbo].[Foundation]
    ADD CONSTRAINT [PK_Foundation] PRIMARY KEY CLUSTERED ([FoundationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

