ALTER TABLE [dbo].[Floor]
    ADD CONSTRAINT [PK_Floor] PRIMARY KEY CLUSTERED ([FloorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

