ALTER TABLE [dbo].[MaintenanceTeam]
    ADD CONSTRAINT [PK_MaintenanceTeam] PRIMARY KEY CLUSTERED ([TeamId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

