ALTER TABLE [dbo].[MaintenanceProvider]
    ADD CONSTRAINT [PK_MaintenanceProvider] PRIMARY KEY CLUSTERED ([MaintenanceProviderId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

