ALTER TABLE [dbo].[MaintenanceCompanySpecialization]
    ADD CONSTRAINT [PK_MaintenanceCompanySpecialization] PRIMARY KEY CLUSTERED ([CompanyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

