ALTER TABLE [dbo].[MaintenanceProviderAcceptedJobs]
    ADD CONSTRAINT [PK_MaintenanceProviderAcceptedJobs] PRIMARY KEY CLUSTERED ([MaintenanceProviderId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

