ALTER TABLE [dbo].[OwnerShowingCalendar]
    ADD CONSTRAINT [PK_OwnerShowingCalendar] PRIMARY KEY CLUSTERED ([EventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

