ALTER TABLE [dbo].[OwnerMaintenance]
    ADD CONSTRAINT [PK_OwnerMaintenance] PRIMARY KEY CLUSTERED ([OwnerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

