ALTER TABLE [dbo].[Owner]
    ADD CONSTRAINT [PK_Owner] PRIMARY KEY CLUSTERED ([OwnerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

