ALTER TABLE [dbo].[Specialist]
    ADD CONSTRAINT [PK_Specialist] PRIMARY KEY CLUSTERED ([SpecialistId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

