ALTER TABLE [dbo].[SpecialistPendingTeamInvitation]
    ADD CONSTRAINT [PK_SpecialistPendingTeamInvitation] PRIMARY KEY CLUSTERED ([PendingTeamInvitationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

