ALTER TABLE [dbo].[ServiceType]
    ADD CONSTRAINT [PK_ServiceType] PRIMARY KEY CLUSTERED ([ServiceTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

