ALTER TABLE [dbo].[Tenant]
    ADD CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED ([TenantId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

