ALTER TABLE [dbo].[TenantSavedSearch]
    ADD CONSTRAINT [PK_TenantSavedSearch] PRIMARY KEY CLUSTERED ([SearchId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

