ALTER TABLE [dbo].[TenantMaintenance]
    ADD CONSTRAINT [PK_TenantMaintenance] PRIMARY KEY CLUSTERED ([MaintenanceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

