ALTER TABLE [dbo].[UnitLuxuryAmenities]
    ADD CONSTRAINT [PK_UnitLuxuryAmenities] PRIMARY KEY CLUSTERED ([UnitId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

