ALTER TABLE [dbo].[UnitCommunityAmenities]
    ADD CONSTRAINT [PK_UnitCommunityAmenities_1] PRIMARY KEY CLUSTERED ([UnitId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

