ALTER TABLE [dbo].[UploadedContract]
    ADD CONSTRAINT [PK_UploadedContract] PRIMARY KEY CLUSTERED ([UploadedImageId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

