ALTER TABLE [dbo].[UrgencyType]
    ADD CONSTRAINT [PK_UrgencyType] PRIMARY KEY CLUSTERED ([UrgencyTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

