ALTER TABLE [dbo].[UnitGallery]
    ADD CONSTRAINT [PK_UnitGallery] PRIMARY KEY CLUSTERED ([UnitGalleryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

