CREATE TABLE [dbo].[GeneratedRentalContract] (
    [ID]                          INT            IDENTITY (1, 1) NOT NULL,
    [LandLoardName]               NVARCHAR (100) NULL,
    [LandLoardRole]               CHAR (10)      NULL,
    [LandLoradID]                 INT            NULL,
    [LandLoardAddress]            NVARCHAR (255) NULL,
    [TenantName]                  NVARCHAR (100) NULL,
    [TenantID]                    INT            NULL,
    [PropertyID]                  INT            NULL,
    [PropertyAddress]             NVARCHAR (255) NULL,
    [PropertyCity]                VARCHAR (128)  NULL,
    [MonthlyRent]                 FLOAT          NULL,
    [BeginingDate]                INT            NULL,
    [StartDate]                   DATE           NULL,
    [EndDate]                     DATE           NULL,
    [FirstMonthRent]              FLOAT          NULL,
    [SecurityDeposit]             FLOAT          NULL,
    [TotalPayment]                FLOAT          NULL,
    [TenantRefundedNumberofDays]  INT            NULL,
    [NoticeofMoveoutNumberofDays] INT            NULL,
    [LateFeeCharge]               FLOAT          NULL,
    [PercentageofLateFeeCharge]   INT            NULL,
    [LateFeeStartingDay]          INT            NULL,
    [ExceptedUtilites]            NVARCHAR (255) NULL,
    [PetDeposit]                  FLOAT          NULL,
    [PetMonthly]                  FLOAT          NULL,
    [ParkingSpaceNumber]          NVARCHAR (50)  NULL,
    [ParkingFee]                  FLOAT          NULL
);

