CREATE TABLE [dbo].[MaintenanceInteriors] (
    [CompanyId]                            INT NOT NULL,
    [Basement Lowering]                    BIT NOT NULL,
    [Basement Remodeling]                  BIT NOT NULL,
    [Bathroom Remodeling]                  BIT NOT NULL,
    [Cabinetry and Built-ins]              BIT NOT NULL,
    [Carpenters]                           BIT NOT NULL,
    [Carpet and Vinyl Floors]              BIT NOT NULL,
    [Ceiling Install and Repair]           BIT NOT NULL,
    [Closets Designing/Organizing]         BIT NOT NULL,
    [Counter Tops]                         BIT NOT NULL,
    [Remodeling]                           BIT NOT NULL,
    [Buffing & Polishing]                  BIT NOT NULL,
    [Drywall]                              BIT NOT NULL,
    [Carpet Installation]                  BIT NOT NULL,
    [Fireplaces & Firewood]                BIT NOT NULL,
    [Floor Heating]                        BIT NOT NULL,
    [Framing]                              BIT NOT NULL,
    [Hardwood and Laminate Flooring]       BIT NOT NULL,
    [Hardwood Floor Refinishing]           BIT NOT NULL,
    [Home Theaters]                        BIT NOT NULL,
    [Hot Tubs, Spas & Jacuzzis]            BIT NOT NULL,
    [Insulation]                           BIT NOT NULL,
    [Decorating & Design]                  BIT NOT NULL,
    [Kitchen Remodeling]                   BIT NOT NULL,
    [Non-Slip Treatments]                  BIT NOT NULL,
    [Painting Services]                    BIT NOT NULL,
    [Solariums and Sunrooms]               BIT NOT NULL,
    [Tile / Tiling]                        BIT NOT NULL,
    [Asbestos Removal]                     BIT NOT NULL,
    [Wallpaper & Wall Coverings & Removal] BIT NOT NULL
);

