CREATE TABLE [dbo].[MaintenanceCompanySpecialization] (
    [CompanyId]                  INT           NOT NULL,
    [NumberofEmployee]           INT           NOT NULL,
    [NumberofCertifitedEmplyee]  INT           NOT NULL,
    [Air Conditioning]           BIT           NOT NULL,
    [Electrical]                 BIT           NOT NULL,
    [Kitchen Remodeling]         BIT           NOT NULL,
    [Architects]                 BIT           NOT NULL,
    [Flooring]                   BIT           NOT NULL,
    [Landscaping]                BIT           NOT NULL,
    [Asphalt Paving]             BIT           NOT NULL,
    [General Contracting]        BIT           NOT NULL,
    [Painting]                   BIT           NOT NULL,
    [Basement Finishing]         BIT           NOT NULL,
    [Handyman Services]          BIT           NOT NULL,
    [Plumbing]                   BIT           NOT NULL,
    [Bathroom Remodeling]        BIT           NOT NULL,
    [Heating]                    BIT           NOT NULL,
    [Roofing]                    BIT           NOT NULL,
    [Concrete]                   BIT           NOT NULL,
    [Home Addition Construction] BIT           NOT NULL,
    [Siding]                     BIT           NOT NULL,
    [Deck Construction]          BIT           NOT NULL,
    [Home Construction]          BIT           NOT NULL,
    [Tiling]                     BIT           NOT NULL,
    [IsInsured]                  BIT           NOT NULL,
    [Rate]                       FLOAT         NOT NULL,
    [Currency]                   NVARCHAR (10) NOT NULL,
    [CurrencyID]                 INT           NOT NULL
);

