CREATE TABLE [dbo].[Unit] (
    [UnitId]          INT            IDENTITY (1, 1) NOT NULL,
    [Bed]             INT            NOT NULL,
    [Bathroom]        FLOAT          NOT NULL,
    [SquareFoot]      FLOAT          NOT NULL,
    [Lot]             FLOAT          NULL,
    [TypeId]          INT            NULL,
    [YearBuilt]       SMALLDATETIME  NULL,
    [YearRemodeled]   SMALLDATETIME  NULL,
    [Description]     NVARCHAR (500) NULL,
    [PrimaryPhoto]    NVARCHAR (MAX) NULL,
    [Address]         NVARCHAR (255) NULL,
    [GoogleMap]       NVARCHAR (MAX) NULL,
    [Country]         VARCHAR (128)  NULL,
    [State]           NVARCHAR (20)  NULL,
    [Region]          VARCHAR (128)  NULL,
    [City]            VARCHAR (128)  NULL,
    [Zip]             NVARCHAR (20)  NULL,
    [CountryCode]     VARCHAR (3)    NULL,
    [NumberofPhoto]   INT            NULL,
    [Price]           FLOAT          NULL,
    [Currency]        NVARCHAR (20)  NULL,
    [CurrencyCode]    INT            NULL,
    [ParkingSpaceId]  INT            NULL,
    [GarageSizeId]    INT            NULL,
    [DaysOnSite]      INT            NULL,
    [FloorId]         INT            NULL,
    [AvailableDate]   SMALLDATETIME  NULL,
    [PosterRole]      CHAR (10)      NULL,
    [PosterID]        INT            NULL,
    [YouTubeVideo]    BIT            NULL,
    [YouTubeVideoURL] NVARCHAR (256) NULL,
    [VimeoVideo]      BIT            NULL,
    [VimeoVideoURL]   NVARCHAR (256) NULL,
    [Title]           NVARCHAR (50)  NULL
);

